#@ load("@ytt:data", "data")
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: golang
  name: golang-test-pipeline
  namespace: #@ data.values.tap.devNamespace
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  tasks:
  - name: go-test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      spec: null
      steps:
      - image: golang
        name: test
        resources: {}
        script: |-
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m
          go test