#@ load("@ytt:data", "data")
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-app-platform"
    kapp.k14s.io/change-rule.1: "upsert after upserting tanzu-app-platform-configs"
    kapp.k14s.io/change-rule.2: "delete after deleting tanzu-app-platform"
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: node
  name: node-test-pipeline
  namespace: #@ data.values.tap.devNamespace
spec:
  params:
    - name: source-url
    - name: source-revision
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: react-test
            image: node
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              npm install
              npm run test -- --watchAll=false