namespace: prod-ns
targetImagePullSecret: "registry-credentials"
snyk:
  tokenSecret:
    name: snyk-token-secret
metadataStore:
  url: "https://metadata-store.tap.tanzu.projectscions.com"
  caSecret:
    importFromNamespace: ""
  authSecret:
    importFromNamespace: ""