#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-ssh
  namespace: #@ data.values.tap.devNamespace
  annotations:
    tekton.dev/git-0: https://ynamadi@dev.azure.com
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.azure_devops.username
  password: #@ data.values.tap.credentials.azure_devops.access_token
