#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign-key-pair
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: Opaque
data:
  cosign.key: #@ data.values.tap.credentials.cosign.cosign_key
  cosign.password: #@ data.values.tap.credentials.cosign.cosign_password
  cosign.pub: #@ data.values.tap.credentials.cosign.cosign_pub
immutable: true