#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token-secret
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
data:
  snyk_token: #@ data.values.tap.credentials.snyk.token