#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ if data.values.tap.devNamespace != "default" and data.values.tap.devNamespace != "":
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-group: "developer-namespace"
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"

---
#@ def config():
#@  return {
#@    "auths": {
#@      data.values.tap.registry.host: {
#@        "username": data.values.tap.credentials.registry.username,
#@        "password": data.values.tap.credentials.registry.password
#@      }
#@    }
#@  }
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-group: "registry-credentials"
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ json.encode(config())
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: #@ data.values.tap.devNamespace
  annotations:
    tekton.dev/git-0: https://github.com
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.github.username
  password: #@ data.values.tap.credentials.github.token
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  namespace: #@ data.values.tap.devNamespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
secrets:
  - name: registry-credentials
  - name: git-ssh
imagePullSecrets:
- name: tap-registry
- name: registry-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
rules:
- apiGroups: [source.toolkit.fluxcd.io]
  resources: [gitrepositories]
  verbs: ['*']
- apiGroups: [source.apps.tanzu.vmware.com]
  resources: [imagerepositories]
  verbs: ['*']
- apiGroups: [carto.run]
  resources: [deliverables, runnables]
  verbs: ['*']
- apiGroups: [kpack.io]
  resources: [images]
  verbs: ['*']
- apiGroups: [conventions.apps.tanzu.vmware.com]
  resources: [podintents]
  verbs: ['*']
- apiGroups: [""]
  resources: ['configmaps']
  verbs: ['*']
- apiGroups: [""]
  resources: ['pods']
  verbs: ['list']
- apiGroups: [tekton.dev]
  resources: [tasks, taskruns, pipelineruns]
  verbs: ['*']
- apiGroups: [tekton.dev]
  resources: [pipelines]
  verbs: ['list']
- apiGroups: [kappctrl.k14s.io]
  resources: [apps]
  verbs: ['*']
- apiGroups: [serving.knative.dev]
  resources: ['services']
  verbs: ['*']
- apiGroups: [servicebinding.io]
  resources: ['servicebindings']
  verbs: ['*']
- apiGroups: [services.apps.tanzu.vmware.com]
  resources: ['resourceclaims']
  verbs: ['*']
- apiGroups: [scanning.apps.tanzu.vmware.com]
  resources: ['imagescans', 'sourcescans']
  verbs: ['*']
- apiGroups: [apis.apps.tanzu.vmware.com]
  resources: ['apidescriptors']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
  - kind: ServiceAccount
    name: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-deliverable
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-workload
  namespace: #@ data.values.tap.devNamespace
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-binding-postgres
  annotations:
    kapp.k14s.io/change-rule.0: "delete after deleting tanzu-app-platform"
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: ["sql.tanzu.vmware.com"]
    resources: ["postgres"]
    verbs: ["get", "list", "watch"]
#@ end
