#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  commonName: '*.tap.tanzu.y-compiles.com'
  secretName: tls
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.tap.tanzu.y-compiles.com'
